services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
#      - ./src:/app/src
      - ./:/app
      - ./migrations:/app/migrations
    env_file:
#      - .env.template
      - .env
    depends_on:
      - mongodb
#    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn src.external.web.fastapi.app:app --host 0.0.0.0 --port 8000 --reload'
    command: bash -c 'uvicorn src.external.web.fastapi.app:app --host 0.0.0.0 --port 8000 --reload'
    networks:
      - app-network

#  migrations:
#    build: .
#    volumes:
#      - ./migrations:/app/migrations
#      - ./src:/app/src
#    env_file:
#      - .env.template
#    depends_on:
#      - mongodb
#    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; alembic -c migrations/alembic/alembic.ini upgrade head"
#    networks:
#      - app-network

#  postgres:
#    image: postgres:16.0-alpine
#    restart: unless-stopped
#    ports:
#      - "5432:5432"
#    volumes:
#      - py_ports_adapters_postgres_data:/var/lib/postgresql/data
#    env_file:
#      - .env.template
#    networks:
#      - app-network

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - fiap_postech_selfservice_fastfood_payment_mongodb_data:/data/db

volumes:
  fiap_postech_selfservice_fastfood_payment_mongodb_data:

networks:
  app-network:
