services:
  api:
    image: alorencatto/fiap-postech-selfservice-fastfood-payment:0.0.1
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
#      - ./src:/app/src
      - ./:/app
      - ./migrations:/app/migrations
    env_file:
#      - .env.dev.template
      - .env.dev
    depends_on:
      - mongodb
    command: bash -c 'uvicorn src.external.web.fastapi.app:app --host 0.0.0.0 --port 8000 --reload'
    networks:
      - app-network

#  mongodb:
#    image: mongodb/mongodb-community-server:6.0-ubi8
#    ports:
#      - "27017:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=user
#      - MONGO_INITDB_ROOT_PASSWORD=pass
#    volumes:
#      - fiap_postech_selfservice_fastfood_payment_mongodb_data:/data/db

volumes:
  fiap_postech_selfservice_fastfood_payment_mongodb_data:

networks:
  app-network:
