apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-fiap-postech-selfservice-fastfood-payment
spec:
  selector:
    app: fiap-postech-selfservice-fastfood-payment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31553
  type: NodePort